import Head from 'next/head'
import { useWallet } from '@solana/wallet-adapter-react'
import { Header } from '@/components/Header'
import { Connected } from '@/components/Connected';
import { Spacer, Box } from '@chakra-ui/react';




export default function Home() {
  const { connected } = useWallet();

  return (
    <>
      <Head>
        <title>Pay Bill & Tax </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>


      <Header />

      <Box
        w='100%'
        h='100vh'
        bgGradient='linear(to-r, gray.300, yellow.400, pink.200)'
      >
        <Spacer />
        {connected && <Connected />}
        <Spacer />

      </Box>


    </>
  )
}
